Requirements updated

diff --git a/karma_v2 b/karma_v2
--- a/karma_v2
+++ b/karma_v2
@@ -281,6 +281,7 @@ args(){
 	interlace_bin="interlace"
 	lolcat_bin="lolcat"
 	jq_bin="jq"
+	anew_bin="anew"
 	python3_bin="python3"
 	nuclei_bin="nuclei"
 	sleep_time="5"
@@ -292,37 +293,42 @@ args(){
 # │		Prerequisites	 │
 # ╰──────────────────────────────╯
 check_requirements(){
-	"$(which ${shodan_bin})" --help > /dev/null 2>&1
+	# shodan && httprobe && interlace && jq
+	$(which "${shodan_bin}") --help > /dev/null 2>&1
 	if [[ ! $? -eq 0 ]]; then
 		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${shodan_bin}. Make sure it installed OR \n\t - pip3 install shodan${end}\n";exit 1
 	fi
-	"$(which ${httprobe_bin})" --help > /dev/null 2>&1 
+	$(which "${httprobe_bin}") --help > /dev/null 2>&1 
 	if [[ ! $? -eq 0 ]]; then
 		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${httprobe_bin}. Make sure it installed OR \n\t - GO111MODULE=on go get -v github.com/tomnomnom/httprobe${end}\n";exit 1
 	fi
-	"$(which ${interlace_bin})" --help > /dev/null 2>&1 
+	$(which "${interlace_bin}") --help > /dev/null 2>&1 
 	if [[ ! $? -eq 0 ]]; then
-	printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${interlace_bin}. Make sure it installed OR \n\t - Clone https://github.com/codingo/Interlace.git${end}\n";exit 1
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${interlace_bin}. Make sure it installed OR \n\t - Clone https://github.com/codingo/Interlace.git${end}\n";exit 1
 	fi
-	"$(which ${jq_bin})" --help > /dev/null 2>&1 
+	$(which "${jq_bin}") --help > /dev/null 2>&1 
 	if [[ ! $? -eq 0 ]]; then
-	printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${jq_bin}. Make sure it installed OR \n\t - apt install jq -y${end}\n";exit 1
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${jq_bin}. Make sure it installed OR \n\t - apt install jq -y${end}\n";exit 1
 	fi
-	"$(which ${lolcat_bin})" --version > /dev/null 2>&1
+	$(which "${lolcat_bin}") --version > /dev/null 2>&1
 	if [[ ! $? -eq 0 ]]; then
-	printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${lolcat_bin}. Make sure it installed OR \n\t - apt install lolcat -y${end}\n";exit 1
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${lolcat_bin}. Make sure it installed OR \n\t - apt install lolcat -y${end}\n";exit 1
 	fi
-	"$(which ${nuclei_bin})" --help > /dev/null 2>&1
+	which "${anew_bin}" > /dev/null 2>&1
 	if [[ ! $? -eq 0 ]]; then
-	printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${nuclei_bin}. Make sure it installed OR \n\t - GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei${end}\n";exit 1
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${anew_bin}. Make sure it installed OR \n\t - GO111MODULE=on go get -u github.com/tomnomnom/anew${end}\n";exit 1
 	fi
-	"$(which ${python3_bin})" --help > /dev/null 2>&1
+	$(which "${nuclei_bin}") --help > /dev/null 2>&1
 	if [[ ! $? -eq 0 ]]; then
-	printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${python3_bin}. Make sure it installed OR \n\t - apt install python3 python3-pip -y${end}\n";exit 1
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${nuclei_bin}. Make sure it installed OR \n\t - GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei${end}\n";exit 1
 	fi
-	"$(which ${python3_bin})" -c 'import mmh3' > /dev/null 2>&1
+	$(which "${python3_bin}") --help > /dev/null 2>&1
 	if [[ ! $? -eq 0 ]]; then
-	printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${python3_bin} mmh3 module. Make sure it installed OR \n\t - ${python3_bin} -m pip install mmh3${end}\n";exit 1
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${python3_bin}. Make sure it installed OR \n\t - apt install python3 python3-pip -y${end}\n";exit 1
+	fi
+	$(which "${python3_bin}") -c 'import mmh3' > /dev/null 2>&1
+	if [[ ! $? -eq 0 ]]; then
+		printf "\n[${red}!${end}] ${yellow}Error: Unable to find ${python3_bin} mmh3 module. Make sure it installed OR \n\t - ${python3_bin} -m pip install mmh3${end}\n";exit 1
 	fi
  }
 # ╭──────────────────────────────╮
